// scriptbundle inlines a script transport's local require("./...") modules
// into one self-contained .js file, so authors can split shared code (e.g.
// the SmartCaptcha solver used by yandex.js/vyandex.js/boards.js) into
// separate files without the runtime ever needing a require() loader: the
// transport's goja Runtime only ever sees the flattened output, exactly the
// same single global-scope script it would eval today. Sign the OUTPUT of
// this tool with scriptsign, not the source files.
//
// Only relative requires ("./foo.js", "../lib/bar.js") are supported - there
// is no host filesystem or package resolution to bundle against. Module
// resolution is a plain regex scan for require(...) calls, not a real JS
// parser: it will misfire on a require(...) that appears inside a string or
// comment. Acceptable for our own authored sources; not meant to bundle
// arbitrary third-party JS.
//
//	scriptbundle -entry transport/script/js/src/yandex.js \
//	  -out transport/script/js/yandex.js
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var requireRe = regexp.MustCompile(`require\(\s*(['"])([^'"]+)['"]\s*\)`)

func main() {
	entry := flag.String("entry", "", "Entry .js file; its top-level code is emitted unwrapped (e.g. `var Transport = {...}` stays a real global)")
	out := flag.String("out", "", "Output bundled .js file")
	flag.Parse()

	if *entry == "" || *out == "" {
		fmt.Fprintln(os.Stderr, "usage: scriptbundle -entry <path> -out <path>")
		os.Exit(2)
	}
	if err := run(*entry, *out); err != nil {
		fmt.Fprintln(os.Stderr, "scriptbundle:", err)
		os.Exit(1)
	}
}

func run(entryPath, outPath string) error {
	entryAbs, err := filepath.Abs(entryPath)
	if err != nil {
		return err
	}
	entryDir := filepath.Dir(entryAbs)

	b := &bundler{entryDir: entryDir, modules: map[string]string{}, order: nil, visiting: map[string]bool{}}

	entryRaw, err := os.ReadFile(entryAbs)
	if err != nil {
		return fmt.Errorf("read entry: %w", err)
	}
	rewrittenEntry, err := b.rewrite(entryDir, string(entryRaw))
	if err != nil {
		return err
	}

	var out strings.Builder
	out.WriteString("// Generated by scriptbundle from " + filepath.Base(entryPath) + " - do not edit directly.\n")
	if len(b.order) > 0 {
		out.WriteString(runtimePrelude)
		for _, id := range b.order {
			out.WriteString("__bundleModules[\"" + id + "\"] = function (module, exports, require) {\n")
			out.WriteString(b.modules[id])
			out.WriteString("\n};\n\n")
		}
	}
	out.WriteString(rewrittenEntry)
	out.WriteString("\n")

	return os.WriteFile(outPath, []byte(out.String()), 0o644)
}

const runtimePrelude = `var __bundleModules = {};
var __bundleCache = {};
function __require(id) {
  if (__bundleCache[id]) { return __bundleCache[id].exports; }
  var mod = { exports: {} };
  __bundleCache[id] = mod;
  if (!__bundleModules[id]) { throw new Error("scriptbundle: unresolved module " + id); }
  __bundleModules[id](mod, mod.exports, __require);
  return mod.exports;
}

`

// bundler resolves and inlines every module reachable from the entry file.
// modules/order are keyed by module id: the required path resolved relative
// to entryDir and slash-normalized, so the same file always gets the same
// id no matter which module requires it.
type bundler struct {
	entryDir string
	modules  map[string]string // id -> rewritten source
	order    []string          // discovery order, sorted before emission
	visiting map[string]bool   // cycle guard
}

// rewrite replaces every require("./x.js") in src (a file living in dir)
// with __require("<id>"), loading and registering that dependency first.
func (b *bundler) rewrite(dir, src string) (string, error) {
	var firstErr error
	out := requireRe.ReplaceAllStringFunc(src, func(m string) string {
		if firstErr != nil {
			return m
		}
		sub := requireRe.FindStringSubmatch(m)
		reqPath := sub[2]
		if !strings.HasPrefix(reqPath, "./") && !strings.HasPrefix(reqPath, "../") {
			firstErr = fmt.Errorf("only relative requires are supported, got %q", reqPath)
			return m
		}
		abs := filepath.Clean(filepath.Join(dir, reqPath))
		id, err := filepath.Rel(b.entryDir, abs)
		if err != nil {
			firstErr = err
			return m
		}
		id = filepath.ToSlash(id)
		if err := b.load(abs, id); err != nil {
			firstErr = err
			return m
		}
		return `__require("` + id + `")`
	})
	if firstErr != nil {
		return "", firstErr
	}
	return out, nil
}

func (b *bundler) load(absPath, id string) error {
	if _, ok := b.modules[id]; ok {
		return nil
	}
	if b.visiting[id] {
		return fmt.Errorf("require cycle detected at %q", id)
	}
	b.visiting[id] = true
	defer delete(b.visiting, id)

	raw, err := os.ReadFile(absPath)
	if err != nil {
		return fmt.Errorf("read module %q: %w", id, err)
	}
	rewritten, err := b.rewrite(filepath.Dir(absPath), string(raw))
	if err != nil {
		return fmt.Errorf("module %q: %w", id, err)
	}
	b.modules[id] = rewritten
	b.order = append(b.order, id)
	sort.Strings(b.order) // deterministic output regardless of discovery order
	return nil
}
